### ISSUE TITLE
Doesn't process *.mpg files

### ISSUE THREAD

**Issue by hoveeman** [djaydev/docker-auto-comskip#1]
https://github.com/djaydev/docker-auto-comskip/blob/ab93b56962fdb82c13d51bb3e43f72232a10d612/rootfs/etc/services.d/autocomskip/run#L105

Please add support to process *.mpg files.

**Comment by djaydev** [comment]
I added the mpg extension.  I can't test it against the included comskip program though because I don't have any mpg files.
